// Generates supabase/seed.sql from the course files in content/courses.
// Usage: npm run content:seed
//
// The seed upserts by deterministic id: re-running it overwrites those courses,
// modules and lessons with the versions in content/. Lessons created in the
// admin area (different ids) are not touched.
import { writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { loadCourses, missingSections, stableId } from './lib/content.mjs';

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const courses = loadCourses(path.join(root, 'content', 'courses'));

const q = (v) => (v === null || v === undefined ? 'null' : `'${String(v).replace(/'/g, "''")}'`);
function dollar(body) {
  let tag = 'md';
  let n = 0;
  while (body.includes(`$${tag}$`)) tag = `md${++n}`;
  return `$${tag}$${body}$${tag}$`;
}

const out = [
  '-- GENERATED by scripts/build-seed.mjs from content/courses. Do not edit by hand.',
  '-- Re-running overwrites these seeded rows (matched by id).',
  'begin;',
];
let lessonCount = 0;

for (const c of courses) {
  const courseId = stableId('course', c.slug);
  out.push(`
insert into public.courses (id, slug, title, subtitle, description, category, icon, position, is_published)
values (${q(courseId)}, ${q(c.slug)}, ${q(c.title)}, ${q(c.subtitle)}, ${q(c.description)}, ${q(c.category)}, ${q(c.icon)}, ${c.position}, true)
on conflict (id) do update set slug = excluded.slug, title = excluded.title, subtitle = excluded.subtitle,
  description = excluded.description, category = excluded.category, icon = excluded.icon,
  position = excluded.position, updated_at = now();`);

  for (const m of c.modules) {
    const missing = missingSections(m.body);
    if (m.status === 'published' && missing.length) {
      throw new Error(`${c.slug}/${m.slug} is published but missing sections: ${missing.join(', ')}`);
    }
    const moduleId = stableId('module', c.slug, m.slug);
    const lessonId = stableId('lesson', c.slug, m.slug);
    lessonCount++;
    out.push(`
insert into public.modules (id, course_id, title, summary, position, is_published)
values (${q(moduleId)}, ${q(courseId)}, ${q(m.title)}, ${q(m.summary)}, ${m.position}, true)
on conflict (id) do update set title = excluded.title, summary = excluded.summary, position = excluded.position, updated_at = now();
insert into public.lessons (id, module_id, course_id, slug, title, summary, duration_minutes, position, is_preview, status)
values (${q(lessonId)}, ${q(moduleId)}, ${q(courseId)}, ${q(m.slug)}, ${q(m.title)}, ${q(m.summary)}, ${m.minutes}, 1, ${m.preview}, ${q(m.status)})
on conflict (id) do update set slug = excluded.slug, title = excluded.title, summary = excluded.summary,
  duration_minutes = excluded.duration_minutes, is_preview = excluded.is_preview, status = excluded.status, updated_at = now();
insert into public.lesson_content (lesson_id, body_md)
values (${q(lessonId)}, ${dollar(m.body)})
on conflict (lesson_id) do update set body_md = excluded.body_md, updated_at = now();`);
  }
}
out.push('\ncommit;\n');

writeFileSync(path.join(root, 'supabase', 'seed.sql'), out.join('\n'));
console.log(`Wrote supabase/seed.sql: ${courses.length} courses, ${lessonCount} lessons.`);
